//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhuDD4_MorckProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cart
    {
        public string cart_id { get; set; }
        public int product_id { get; set; }
        public Nullable<int> product_number { get; set; }
    
        public virtual customer customer { get; set; }
        public virtual product product { get; set; }
    }
}
