//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhuDD4_MorckProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class don_hang_chitiet
    {
        public int order_id { get; set; }
        public int product_id { get; set; }
        public string product_name { get; set; }
        public Nullable<int> product_number { get; set; }
        public Nullable<decimal> product_dongia { get; set; }
    
        public virtual don_dat_hang don_dat_hang { get; set; }
    }
}
